### ISSUE TITLE
Redis failed while compiling with clang patched

### ISSUE THREAD

**Issue by Nivekiba** [chestnut-sandbox/Chestnut#1]
Hello, i'm trying to use your tools and I have a problem while compiling redis with clang patched with sourcalyser patch.

Here are the commands I used to compile redis after decompress the archive file:
`cd redis-stable`
then:
`CC="/tmp/Chestnut/Sourcealyzer/llvm-project/build/bin/clang -v" make`

I got this error:
![image](https://user-images.githubusercontent.com/20845649/147938329-ac8ac9b7-b35a-490e-b691-88ae40ff779d.png)

But when I used the `clang` I installed through `sudo apt` there is no error.

**Comment by cc0x1f** [comment]
The error here is that /usr/bin/ld is used instead of our modified linker. If you want to use Sourcealyzer, you need to bootstrap a full environment that ensures that always the correct compiler, linker, and libraries are used. We used conan to set up this environment. If you don't set such an environment up, then you will constantly run into errors as the wrong binaries or libraries are used.
